// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEac-2-e1wqZgsTYrHSvQy9qZg0dphQJI',
    appId: '1:526803775982:web:d2ebf1509a5aad7f715eff',
    messagingSenderId: '526803775982',
    projectId: 'expense-tracker-6cd7e',
    authDomain: 'expense-tracker-6cd7e.firebaseapp.com',
    storageBucket: 'expense-tracker-6cd7e.firebasestorage.app',
    measurementId: 'G-MH91LEE6TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsJHpoYOdzR6mNmpZ8L4kTNTZX35e2Sy8',
    appId: '1:526803775982:android:1af7de5ff8f68138715eff',
    messagingSenderId: '526803775982',
    projectId: 'expense-tracker-6cd7e',
    storageBucket: 'expense-tracker-6cd7e.firebasestorage.app',
  );
}
